version: "3.8"

services:
  konusmalar-web:
    build: .
    container_name: konusmalar-web
    ports:
      - "8085:80"
    environment:
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
    restart: unless-stopped
